In [1]:
import numpy as np

In [4]:
a=[0,1,2,3,4]
b=[9,8,7,6,5]
def pysum(a,b):
    tlist=[]
    for i in range(len(a)):
        tlist.append(a[i]**2+b[i]**3)
    return tlist
%timeit pysum(a,b)

3.59 µs ± 53.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [3]:
a=np.array([0,1,2,3,4])
b=np.array([9,8,7,6,5])
%timeit a**2+b**3

2.92 µs ± 91.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [18]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [22]:
c=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(c.shape)#对象的尺度（m*n）
print(c.size)

(2, 5)
10


In [6]:
# print(np.zeros((2,3,3)))
# print(np.ones((2,3,4)))
print(np.eye(5))#单位矩阵

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [49]:
print("生成指定形状的0-1之间随机数组")
print(np.random.random((2,2)))
print("生成指定形状的随机数组")
print(np.random.randint(0,3,(2,2)))
print(np.random.uniform(0,3,(2,2)))
print(np.random.choice(a))
l=['a','b','c','d']
np.random.shuffle(l)
print(l)

生成指定形状的0-1之间随机数组
[[0.28293242 0.15697794]
 [0.43980638 0.5488846 ]]
生成指定形状的随机数组
[[1 0]
 [2 1]]
[[0.28780803 2.53807482]
 [2.62522902 1.60519689]]
4
['a', 'd', 'c', 'b']


In [54]:
print(np.random.normal(0,1,(3,3)))
print(np.random.randn(3,3))

[[ 1.53739588  0.11521509 -1.79394564]
 [ 1.21970728 -1.27589493  1.40671151]
 [-0.98168914  0.40710985  0.43163451]]
[[-0.24361432  0.22773791 -0.28357626]
 [-0.38578624  0.55939357 -0.52773765]
 [-0.63471153  0.48028531  0.57921656]]


In [7]:
# print(np.arange(1,10,2))
print(np.linspace(0,10,5))#等距离分布
print(np.linspace(0,10,5,endpoint=False))#不包含末尾元素
print(np.arange(10).reshape(2,5)) #reshape修改元素形状
# print(np.arange(10).reshape(5,2))
# print(np.arange(100).reshape(10,-1))
# print(np.arange(100).reshape(-1,4))

[ 0.   2.5  5.   7.5 10. ]
[0. 2. 4. 6. 8.]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [67]:
# 数组的索引和切片
print("数组的索引")
a=np.arange(10)
print(a)
print(a[0],a[1])
print(a[-1],a[-2])
print(a[0:2])
print(a[0:20])

数组的索引
[0 1 2 3 4 5 6 7 8 9]
0 1
9 8
[0 1]
[0 1 2 3 4 5 6 7 8 9]


In [73]:
# 多维数组的索引切片
a=np.arange(24).reshape(2,3,4)
print(a)
print(a.ndim,a.shape)
print(a[1,2,3])
print(a[1,0:2,1:3])
print(a[1,0:2,:])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3 (2, 3, 4)
23
[[13 14]
 [17 18]]
[[12 13 14 15]
 [16 17 18 19]]


In [77]:
arr=np.arange(32).reshape(4,8)
print(arr)
print("-"*30)
print(arr[1,[4,5,7]])
print(arr[[0,1,2,3,1],[1,2,4,5,7]])

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
------------------------------
[12 13 15]
[ 1 10 20 29 15]


In [82]:
# 数据类型转换
a=np.arange(12)
print(a.dtype)
b=a.astype(np.float)
print(b.dtype)
print(a)
print(b)

int32
float64
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [84]:
# 数组元素的修改
a=np.arange(12,0,-1).reshape(3,4)
a[0,0]=-12
b=a[0:2,0:2]#得到原数组的视图
b[0,0]=-12
print(a)
print(b)
c=a[0:2,0:2].copy()
c[-1,-1]=100
print(a)
print(c)

[[-12  11  10   9]
 [  8   7   6   5]
 [  4   3   2   1]]
[[-12  11]
 [  8   7]]
[[-12  11  10   9]
 [  8   7   6   5]
 [  4   3   2   1]]
[[-12  11]
 [  8 100]]


In [14]:
# 数组拼接
# x=np.arange(1,4)
# y=np.arange(4,7)
# print(x)
# print(y)
# print(np.concatenate([x,y]))
x=np.arange(4).reshape(2,-1)
y=np.arange(9,13).reshape(2,2)
z=np.arange(4).reshape(2,2)
# print(x)
# print(y)
print(np.concatenate([x,y],axis=0))  #行方向拼接需要保证其他轴相同
print(np.concatenate([x,y],axis=1))    #列方向拼接需要保证其他轴相同
print(np.vstack([x,y]))  #沿第一个轴方向拼接
print(np.hstack([x,z]))  #沿第二个轴方向拼接

[[ 0  1]
 [ 2  3]
 [ 9 10]
 [11 12]]
[[ 0  1  9 10]
 [ 2  3 11 12]]
[[ 0  1]
 [ 2  3]
 [ 9 10]
 [11 12]]
[[0 1 0 1]
 [2 3 2 3]]


In [15]:
x=np.arange(48).reshape(2,3,4,2)
y=np.arange(-48,0).reshape(2,3,4,2)
print(x.shape)
print(y.shape)
print(np.concatenate([x,y],axis=0).shape)
print(np.concatenate([x,y],axis=1).shape)
print(np.concatenate([x,y],axis=2).shape)

(2, 3, 4, 2)
(2, 3, 4, 2)
(4, 3, 4, 2)
(2, 6, 4, 2)
(2, 3, 8, 2)


In [102]:
# 数组的分割
x=np.arange(10,20)
print(x)
print(np.split(x,[3,6]))
x=np.arange(20).reshape(4,5)
print(x)
print("vsplit沿第一个轴进行分割",np.vsplit(x,[1,3]))
print("hsplit沿第一个轴进行分割",np.hsplit(x,[1,3]))

[10 11 12 13 14 15 16 17 18 19]
[array([10, 11, 12]), array([13, 14, 15]), array([16, 17, 18, 19])]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
vsplit沿第一个轴进行分割 [array([[0, 1, 2, 3, 4]]), array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19]])]
hsplit沿第一个轴进行分割 [array([[ 0],
       [ 5],
       [10],
       [15]]), array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]]), array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])]


In [105]:
# 数组的标量计算(广播计算)
a=np.arange(6).reshape(2,3)
print(a)
print(a+1)
print(a*2)

[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]
[[ 0  2  4]
 [ 6  8 10]]


In [106]:
# 数组的计算
a=np.arange(6).reshape(2,3)
b=np.arange(6).reshape(2,3)
a+b

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [110]:
# 一元函数
np.random.seed(0)
a=np.random.randint(-10,100,size=(2,5))
print(a)
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))
print(np.mean(a,axis=1))
print(np.median(a,axis=1))

[[34 37 54 57 57]
 [93 -1 73 11 26]]
441
[127  36 127  68  83]
[239 202]
[47.8 40.4]
[54. 26.]


In [123]:
print(np.prod(a))
print(np.sqrt(np.abs(a)))
print(np.square(a))
b=np.random.uniform(1,3,(3,3))
print(np.rint(b))

-1281166184
[[5.83095189 6.08276253 7.34846923 7.54983444 7.54983444]
 [9.64365076 1.         8.54400375 3.31662479 5.09901951]]
[[1156 1369 2916 3249 3249]
 [8649    1 5329  121  676]]
[[2. 2. 3.]
 [1. 3. 2.]
 [3. 2. 2.]]


In [121]:
# 数学函数
# print(np.log(np.abs(a)))
# print(np.log2(np.abs(a)))
# print(np.exp(np.abs(a)))
# print(np.power(3,a))
print(np.sin(1))

0.8414709848078965


In [127]:
a=np.arange(10)
b=np.arange(5,15)
print(a);print(b)
print(np.isin(a,b))

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[False False False False False  True  True  True  True  True]


In [129]:
# 效率测试
a=np.random.randint(1,10,size=10)
print(a)
%timeit a**1000

[1 1 5 6 6 7 9 5 2 5]
1.51 µs ± 9.86 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [132]:
# 转置
a=np.arange(12).reshape(3,4)
print(a)
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
